spring.application.name=backend

# DB設定
spring.datasource.url=jdbc:postgresql://localhost:5432/my_app
spring.datasource.username=admin
spring.datasource.password=8b2brksk1582SQL
# Entityクラスからテーブルを自動生成する設定です。
# spring.jpa.hibernate.ddl-auto=update

#Hibernateが実行するSQLをコンソールに表示します。
spring.jpa.show-sql=true

#メッセージの外出し用
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# 256bit以上の十分に長い秘密鍵を設定する
jwt.secret=abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ

# アクセストークン有効期限（1時間）
jwt.expiration=3600000