spring.application.name=backend

# DB設定
spring.datasource.url=jdbc:postgresql://localhost:5432/my_app
spring.datasource.username=admin
spring.datasource.password=8b2brksk1582SQL
# Entityクラスからテーブルを自動生成する設定です。
# spring.jpa.hibernate.ddl-auto=update

#Hibernateが実行するSQLをコンソールに表示します。
spring.jpa.show-sql=true

